// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0X98Pvs_SJo4TH62galA_cOPaIPXuGuk',
    appId: '1:218657324735:web:0ea14b7e5bb59caebfd00a',
    messagingSenderId: '218657324735',
    projectId: 'instantchatproject',
    authDomain: 'instantchatproject.firebaseapp.com',
    storageBucket: 'instantchatproject.firebasestorage.app',
    measurementId: 'G-FBSEDE8CW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn4m5j1k4OPs3Bcn04bzvJ-AgHp5-23GM',
    appId: '1:218657324735:android:af298a3dffa3102fbfd00a',
    messagingSenderId: '218657324735',
    projectId: 'instantchatproject',
    storageBucket: 'instantchatproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmDZzDil-ujgPo1ItDwunE9w1XAR74H6E',
    appId: '1:218657324735:ios:f4e0ca0c76ffeacabfd00a',
    messagingSenderId: '218657324735',
    projectId: 'instantchatproject',
    storageBucket: 'instantchatproject.firebasestorage.app',
    iosBundleId: 'com.example.rezatestoctapullapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmDZzDil-ujgPo1ItDwunE9w1XAR74H6E',
    appId: '1:218657324735:ios:f4e0ca0c76ffeacabfd00a',
    messagingSenderId: '218657324735',
    projectId: 'instantchatproject',
    storageBucket: 'instantchatproject.firebasestorage.app',
    iosBundleId: 'com.example.rezatestoctapullapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0X98Pvs_SJo4TH62galA_cOPaIPXuGuk',
    appId: '1:218657324735:web:90c9c4c52a7a0c1abfd00a',
    messagingSenderId: '218657324735',
    projectId: 'instantchatproject',
    authDomain: 'instantchatproject.firebaseapp.com',
    storageBucket: 'instantchatproject.firebasestorage.app',
    measurementId: 'G-492DW3276S',
  );

}