// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACg-PnXRzyyzDbX-kXi4u90N-aTSefuvg',
    appId: '1:2564682331:web:464e7479f6e2a94f59457e',
    messagingSenderId: '2564682331',
    projectId: 'instantchattest',
    authDomain: 'instantchattest.firebaseapp.com',
    storageBucket: 'instantchattest.firebasestorage.app',
    measurementId: 'G-K3FBHW3WWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8TKfGEJRTJB8mZSDMcCu0DzBkUvGGpak',
    appId: '1:2564682331:android:80beb1ed8db9b13759457e',
    messagingSenderId: '2564682331',
    projectId: 'instantchattest',
    storageBucket: 'instantchattest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzK9JM5l2wXU7PINod2zEQDfwYP8qiMrw',
    appId: '1:2564682331:ios:b413d1418611bc9b59457e',
    messagingSenderId: '2564682331',
    projectId: 'instantchattest',
    storageBucket: 'instantchattest.firebasestorage.app',
    iosBundleId: 'com.example.rezatestoctapullapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzK9JM5l2wXU7PINod2zEQDfwYP8qiMrw',
    appId: '1:2564682331:ios:b413d1418611bc9b59457e',
    messagingSenderId: '2564682331',
    projectId: 'instantchattest',
    storageBucket: 'instantchattest.firebasestorage.app',
    iosBundleId: 'com.example.rezatestoctapullapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACg-PnXRzyyzDbX-kXi4u90N-aTSefuvg',
    appId: '1:2564682331:web:e03a687f35ab1b6259457e',
    messagingSenderId: '2564682331',
    projectId: 'instantchattest',
    authDomain: 'instantchattest.firebaseapp.com',
    storageBucket: 'instantchattest.firebasestorage.app',
    measurementId: 'G-CFWVKPQZSE',
  );

}