// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYhT5uQl1MBa83bxMkpVXDIb984QR5kHg',
    appId: '1:162699215281:web:35416d461e648e57d4fd90',
    messagingSenderId: '162699215281',
    projectId: 'rizatestoctapulapp',
    authDomain: 'rizatestoctapulapp.firebaseapp.com',
    storageBucket: 'rizatestoctapulapp.firebasestorage.app',
    measurementId: 'G-HM6DQN85BL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9K9wURqnewVsBFw7FVBLkPnq_tFDhB-w',
    appId: '1:162699215281:android:51e25d867ae1defcd4fd90',
    messagingSenderId: '162699215281',
    projectId: 'rizatestoctapulapp',
    storageBucket: 'rizatestoctapulapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoqA2-Zcud6DJ-vBCwEzUulrsmPav-tgk',
    appId: '1:162699215281:ios:91242b290b29de48d4fd90',
    messagingSenderId: '162699215281',
    projectId: 'rizatestoctapulapp',
    storageBucket: 'rizatestoctapulapp.firebasestorage.app',
    iosBundleId: 'com.example.rezatestoctapullapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoqA2-Zcud6DJ-vBCwEzUulrsmPav-tgk',
    appId: '1:162699215281:ios:91242b290b29de48d4fd90',
    messagingSenderId: '162699215281',
    projectId: 'rizatestoctapulapp',
    storageBucket: 'rizatestoctapulapp.firebasestorage.app',
    iosBundleId: 'com.example.rezatestoctapullapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYhT5uQl1MBa83bxMkpVXDIb984QR5kHg',
    appId: '1:162699215281:web:74326cc3a4258f1fd4fd90',
    messagingSenderId: '162699215281',
    projectId: 'rizatestoctapulapp',
    authDomain: 'rizatestoctapulapp.firebaseapp.com',
    storageBucket: 'rizatestoctapulapp.firebasestorage.app',
    measurementId: 'G-0032LH9WQ5',
  );
}
